parameters:
    models: CDAE
    similarity: Cosine
    corruption: [0.2, 0.3, 0.4, 0.5]
    alpha: [1]
    rank: [50, 100, 200]
    root: [1.0]
    topK: [5, 10, 15, 20, 50]
    iter: 300
    lambda: [0.000001]
    metric: [R-Precision, NDCG, Precision, Recall]